/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ge_gov_mia_javacomapi_Native */

#ifndef _Included_ge_gov_mia_javacomapi_Native
#define _Included_ge_gov_mia_javacomapi_Native
#ifdef __cplusplus
extern "C" {
#endif
#undef ge_gov_mia_javacomapi_Native_SUCCESS
#define ge_gov_mia_javacomapi_Native_SUCCESS 0L
#undef ge_gov_mia_javacomapi_Native_ERROR
#define ge_gov_mia_javacomapi_Native_ERROR -1L
#undef ge_gov_mia_javacomapi_Native_NO_DATA
#define ge_gov_mia_javacomapi_Native_NO_DATA -2L
/*
 * Class:     ge_gov_mia_javacomapi_Native
 * Method:    open
 * Signature: (IJIII)J
 */
JNIEXPORT jlong JNICALL Java_ge_gov_mia_javacomapi_Native_open
  (JNIEnv *, jobject, jint, jlong, jint, jint, jint);

/*
 * Class:     ge_gov_mia_javacomapi_Native
 * Method:    close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ge_gov_mia_javacomapi_Native_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ge_gov_mia_javacomapi_Native
 * Method:    read
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ge_gov_mia_javacomapi_Native_read
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ge_gov_mia_javacomapi_Native
 * Method:    write
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ge_gov_mia_javacomapi_Native_write
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
